# Generated by Django 5.1.4 on 2025-01-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
